site_name: Legoraft's wiki

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - rust
    - nginx

nav:
  - Home: 'index'
  - About: 'about'
  - 'Linux':
    - 'Debian': 'debian'
  - 'Command Line':
    - 'Mkvtoolnix': 'mkvtoolnix'
  - 'Servers':
    - 'Info': 'info'
    - 'Nginx': 'nginx'