site_name: Legoraft's wiki

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - rust
    - nginx

Nav:
  - 'index.md'
  - 'about.md'
  - 'Linux':
    - 'debian.md'
  - 'Command Line':
    - 'mkvtoolnix.md'
  - 'Servers':
    - 'info.md'
    - 'nginx.md'