site_name: Legoraft's wiki

site_url: https://legoraft.com/wiki

nav:
  - Home: index.md
  - Tech:
      - Linux:
        - Void Linux: linux/void.md
        - Post install: linux/post-install.md
      - Applications:
        - applications/zsh.md
        - applications/stow.md
  - Homelab:
      - homelab/index.md
      - Docker: homelab/docker.md
      - Applications:
        - homelab/dockge.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
      icon: material/brightness-2
      name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
      icon: material/brightness-7
      name: Switch to light mode
      
  language: en
      
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://mastodon.social/@legoraft
    - icon: fontawesome/brands/github
      link: https://github.com/legoraft