site_name: Legoraft's wiki

site_url: https://legoraft.com/wiki

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
      icon: material/brightness-2
      name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
      icon: material/brightness-7
      name: Switch to light mode
      
    - primary: teal
    - accent: light green

  highlightjs: true
  hljs_languages:
    - rust
    - bash
    - nginx
