site_name: Legoraft's wiki

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - rust
    - nginx

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - 'Linux':
    - 'Debian': 'debian.md'
  - 'Command Line':
    - 'Mkvtoolnix': 'mkvtoolnix.md'
  - 'Servers':
    - 'Info': 'info.md'
    - 'Nginx': 'nginx.md'